#ifndef MG_BLOCKCIPHER_TEST_H
#define MG_BLOCKCIPHER_TEST_H

#include <stdio.h>

enum MG_CRYPTO_TEST_ID {
    MG_CRYPTO_TEST_ID_AES128, // 0
    MG_CRYPTO_TEST_ID_AES192,
    MG_CRYPTO_TEST_ID_AES256,
    MG_CRYPTO_TEST_ID_ARIA128,
    MG_CRYPTO_TEST_ID_ARIA192,
    MG_CRYPTO_TEST_ID_ARIA256,
    MG_CRYPTO_TEST_ID_LEA128,
    MG_CRYPTO_TEST_ID_LEA192,
    MG_CRYPTO_TEST_ID_LEA256,
};

#endif // MG_BLOCKCIPHER_TEST_H