#ifndef MG_BLOCKCIPHER_TEST_H
#define MG_BLOCKCIPHER_TEST_H

#include <stdio.h>

enum MG_CRYPTO_TEST_ID_KAT {
    MG_CRYPTO_TEST_ID_KAT_AES128_ECB, // 0
    MG_CRYPTO_TEST_ID_KAT_AES128_CBC,
    MG_CRYPTO_TEST_ID_KAT_AES128_CTR,
    MG_CRYPTO_TEST_ID_KAT_AES192_ECB,
    MG_CRYPTO_TEST_ID_KAT_AES192_CBC,
    MG_CRYPTO_TEST_ID_KAT_AES192_CTR,
    MG_CRYPTO_TEST_ID_KAT_AES256_ECB,
    MG_CRYPTO_TEST_ID_KAT_AES256_CBC,
    MG_CRYPTO_TEST_ID_KAT_AES256_CTR,
    MG_CRYPTO_TEST_ID_KAT_ARIA128_ECB,
    MG_CRYPTO_TEST_ID_KAT_ARIA128_CBC,
    MG_CRYPTO_TEST_ID_KAT_ARIA128_CTR,
    MG_CRYPTO_TEST_ID_KAT_ARIA192_ECB,
    MG_CRYPTO_TEST_ID_KAT_ARIA192_CBC,
    MG_CRYPTO_TEST_ID_KAT_ARIA192_CTR,
    MG_CRYPTO_TEST_ID_KAT_ARIA256_ECB,
    MG_CRYPTO_TEST_ID_KAT_ARIA256_CBC,
    MG_CRYPTO_TEST_ID_KAT_ARIA256_CTR,
    MG_CRYPTO_TEST_ID_KAT_LEA128_ECB,
    MG_CRYPTO_TEST_ID_KAT_LEA128_CBC,
    MG_CRYPTO_TEST_ID_KAT_LEA128_CTR,
    MG_CRYPTO_TEST_ID_KAT_LEA192_ECB,
    MG_CRYPTO_TEST_ID_KAT_LEA192_CBC,
    MG_CRYPTO_TEST_ID_KAT_LEA192_CTR,
    MG_CRYPTO_TEST_ID_KAT_LEA256_ECB,
    MG_CRYPTO_TEST_ID_KAT_LEA256_CBC,
    MG_CRYPTO_TEST_ID_KAT_LEA256_CTR,
};

#endif // MG_BLOCKCIPHER_TEST_H